title: Bulk RNA-seq quantification pipeline
description: A reliable and efficient pipeline for bulk RNA-seq quantification analysis 
theme: just-the-docs

url: https://qingfeipan.github.io/bulkRNAseq/

aux_links:
  Template Repository: https://qingfeipan.github.io/bulkRNAseq/
