title: Bulk RNA-seq quantification pipeline
description: A reliable and efficient pipeline for bulk RNA-seq quantification analysis 
theme: just-the-docs

url: https://qingfeipan.github.io/bulkRNAseq/

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

aux_links:
  Template Repository: https://qingfeipan.github.io/bulkRNAseq/
